# Generated by Django 5.2.15 on 2026-06-22 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asteroide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('tamanho', models.FloatField()),
                ('distancia', models.FloatField()),
                ('ferro', models.FloatField()),
                ('niquel', models.FloatField()),
                ('platina', models.FloatField()),
                ('agua', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Nave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('velocidade_mineracao', models.FloatField()),
                ('capacidade_maxima', models.FloatField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mineracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_minerado', models.FloatField()),
                ('valor_ganho', models.FloatField()),
                ('data', models.CharField(max_length=20)),
                ('asteroide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.asteroide')),
                ('nave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nave')),
            ],
        ),
    ]
